"""add follow model

Revision ID: 2bc76810d9be
Revises: 99b2833594b2
Create Date: 2017-05-27 21:50:20.369927

"""

# revision identifiers, used by Alembic.
revision = '2bc76810d9be'
down_revision = '99b2833594b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
