"""avatar hash migration

Revision ID: 3e15d829bb48
Revises: bb61f3334a17
Create Date: 2017-05-27 04:21:02.486452

"""

# revision identifiers, used by Alembic.
revision = '3e15d829bb48'
down_revision = 'bb61f3334a17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
