"""add roles

Revision ID: 504b785dbd6c
Revises: 7e1ad0e3cd43
Create Date: 2017-05-27 00:47:58.152557

"""

# revision identifiers, used by Alembic.
revision = '504b785dbd6c'
down_revision = '7e1ad0e3cd43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(u'ix_roles_default', 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_roles_default', table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
