"""add posts model

Revision ID: 61292ce4e1f8
Revises: 3e15d829bb48
Create Date: 2017-05-27 04:28:36.180049

"""

# revision identifiers, used by Alembic.
revision = '61292ce4e1f8'
down_revision = '3e15d829bb48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_posts_timestamp', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
