"""add body_html on model

Revision ID: 6966ab98bb5d
Revises: 75a0b446c7e5
Create Date: 2017-05-27 19:58:58.351198

"""

# revision identifiers, used by Alembic.
revision = '6966ab98bb5d'
down_revision = '75a0b446c7e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
