"""fix author

Revision ID: 726733d6ddba
Revises: 3544b5b6c685
Create Date: 2017-05-28 00:14:12.447635

"""

# revision identifiers, used by Alembic.
revision = '726733d6ddba'
down_revision = '3544b5b6c685'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
