"""change timestamp model

Revision ID: 75a0b446c7e5
Revises: 61292ce4e1f8
Create Date: 2017-05-27 16:28:15.649086

"""

# revision identifiers, used by Alembic.
revision = '75a0b446c7e5'
down_revision = '61292ce4e1f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
