"""change user model

Revision ID: 7e1ad0e3cd43
Revises: d888a6139dae
Create Date: 2017-05-26 00:34:52.125820

"""

# revision identifiers, used by Alembic.
revision = '7e1ad0e3cd43'
down_revision = 'd888a6139dae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
