"""add profiles

Revision ID: bb61f3334a17
Revises: b153adef93d6
Create Date: 2017-05-27 01:24:33.058157

"""

# revision identifiers, used by Alembic.
revision = 'bb61f3334a17'
down_revision = 'b153adef93d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
