"""migrate

Revision ID: cf808f06d215
Revises: 726733d6ddba
Create Date: 2017-06-11 20:28:54.143529

"""

# revision identifiers, used by Alembic.
revision = 'cf808f06d215'
down_revision = '726733d6ddba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
